# Generated by Django 5.2 on 2026-03-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='leavetype',
            name='color',
            field=models.CharField(default='primary', help_text='Bootstrap color (primary, success, danger, warning, info, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='icon',
            field=models.CharField(default='bi-calendar', help_text='Bootstrap icon class', max_length=50),
        ),
    ]
